apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-service
  template:
    metadata:
      labels:
        app: python-service
    spec:
      containers:
      - name: python-container
        image: my-python-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
