apiVersion: v1
kind: Service
metadata:
  name: python-service
spec:
  type: NodePort
  selector:
    app: python-service
  ports:
  - port: 80           # service port
    targetPort: 5000   # container port
    nodePort: 30007    # optional: specify a NodePort in range 30000–32767
